# Generated by Django 4.2.5 on 2023-10-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="listings", new_name="listing",
        ),
    ]
