# Generated by Django 4.2.5 on 2023-10-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="is_pubished", new_name="is_published",
        ),
    ]
